# Generated by Django 5.1 on 2024-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingrediants', models.CharField(max_length=500)),
                ('instrucctions', models.CharField(max_length=2000)),
            ],
        ),
    ]
