# Generated by Django 5.1 on 2024-08-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_date',
        ),
    ]
