# Generated by Django 5.1 on 2024-08-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_signup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instrucctions',
            new_name='instructions',
        ),
    ]
